### ISSUE TITLE
Cannot connect to OPC Ua

### ISSUE THREAD

**Issue by SINIZOWN** [point85/OEE-Designer#21]
Hi,

I try to connect to a OPC Ua Server but got this message : 

![image](https://github.com/point85/OEE-Designer/assets/122884213/bd4972bd-3034-45aa-afd8-23a78757560e)

If I use the same configuration with UAEXPERT it works:

![image](https://github.com/point85/OEE-Designer/assets/122884213/c8f636c7-532a-4674-9733-f8fb4bf2adc7)

And then I've to trust the certificat from UA Expert but with Point 385, I don't receive the certificate request.
![image](https://github.com/point85/OEE-Designer/assets/122884213/592e680d-b3c3-45dc-bc95-101d64ce72b7)

I tried several times with several configurations but it doesn't seem to work, here is the log
![image](https://github.com/point85/OEE-Designer/assets/122884213/99b0eab7-5efb-48ca-a1b8-89536006b6e0)

Can you help me,

Thanks,

Kevin.

**Comment by point85** [comment]
Hello Sinizown,
Could you please send me the entire Point85.log file from the connection
attempt?  Also, would you be able to try first connecting without a
certificate (i.e. basic authentication) to make sure that works?  And
finally, in the log4j2.xml file, please uncomment this entry:

  

and change the level to debug to generate more detailed information from
the Milo OPC UA client.

Regards,
Kent Randall

**Comment by SINIZOWN** [comment]
Hello Kent,

Thanks for your reply, 
Do you mean trying with security policy none? If yes, here is the result. 
![image](https://github.com/point85/OEE-Designer/assets/122884213/ffc780cf-6cbf-4dd1-9272-03e43c58d064)

here is the log with security policy none and Message Security Mode none
![image](https://github.com/point85/OEE-Designer/assets/122884213/5e347bc3-4c70-4d5f-b5ec-009448c3e666)

With Basic256Sha256 and Message Security Mode None
![image](https://github.com/point85/OEE-Designer/assets/122884213/02280581-a68b-4d5a-b99b-0d201c8d91b7)

With Basic256Sha256 and Message Security Mode Sign
![image](https://github.com/point85/OEE-Designer/assets/122884213/7aae66cc-72ae-495f-8b15-34f3dba510f4)

I'm trying to connect to the OPC UA server of ABB's 800xA DCS, I'm not sure if I can connect without a certificate.
You will find the full log with the level debug as attachement 
[Point85.log](https://github.com/point85/OEE-Designer/files/15129777/Point85.log)

**Comment by point85** [comment]
Hello Sinizown,
I would like to look at the Point85 log for the combination of security and
authentication settings that work for the UaExpert.  These values are in
the two tabs "Security Settings" and "Authentication Settings" in the OPC
UA editor, in particular the keystore.

Thanks for the info,
Kent

**Comment by KevinDeGeyter** [comment]
Hello Kent,

On the left you will find the settings for UA Expert, I use authentication settings Anonymous.

And on the right the settings in Point85
![image](https://github.com/point85/OEE-Designer/assets/153553345/ee6a594a-27a8-42cf-88f1-a3e6ab109c0b)

I didn't put anything for the keystore, what should I put in there?
![image](https://github.com/point85/OEE-Designer/assets/153553345/65d6f854-2339-4c45-97e5-00927dfbb807)

On UA expert, I have to check this box to make it work
![image](https://github.com/point85/OEE-Designer/assets/153553345/384902bb-7395-4171-9abd-1d19a36d6876)

Thanks for your help
Kevin.

**Comment by KevinDeGeyter** [comment]
Update :
I've launch this file : 
![image](https://github.com/point85/OEE-Designer/assets/153553345/495a635d-e205-46ad-ae85-26acc93902be)

and try with this 2 keystore : 
![image](https://github.com/point85/OEE-Designer/assets/153553345/3bc201c4-d9aa-4e9c-ac05-e65cc4e76f71)
With the password : Point85 
I got this message : 
![image](https://github.com/point85/OEE-Designer/assets/153553345/2911658f-2894-4b64-b99e-41b42c7fb1fe)

**Comment by point85** [comment]
First, just to review the Point85 OPC UA security settings.  There are two
categories: (1) Security Settings and (2) Authentication Settings.  Under
Security, there is Security Policy and Message Security Mode.  From the
UAExpert screen capture, your security policy is Basic256Sha256 and message
mode Sign & Encrypt.  Therefore you need the same values in Point85.  Now,
on the Authentication settings, Point85 does not have an "accept the X509
certificate temporarily" setting.  But, it has all the other settings in
UAExpert.  Point85 requires the same key file in the config/security folder
that the ABB server expects, since you told me in an earlier email that the
server will not accept Anonymous.

On page 56 of the Point85 User Guide is this instruction:
"Under the Authentication Settings tab, the Java keystore file name can be
specified in the Keystore text field and its password in the Password text
field. The keystore file must be placed in the config/security folder. The
user name and user password text fields can be used to specify the user
name and password for user authentication. The button to the right of the
keystore file name clears out these security settings."

The steps are:
(1)  Get UAExpert to work without the "temporary" setting.  This will
involve finding the OPC UA server keystore file and putting it in a folder
that UAExpert expects.  Note that you can use the Java keytool to list what
certificates are in a keystore file from the command line like this: "keytool
-list -keystore <client keystore file name".
(2) Copy the keystore file to config/settings folder
(3)  Configure the same settings in Point85, and be sure to set the
keystore file name in the "Keystore" text box.

Regards,
Kent Randall
