### ISSUE TITLE
Web application possibility

### ISSUE THREAD

**Issue by vraghu1983** [point85/OEE-Designer#5]
Hi - wanted to check what is the feasiility of converting these stand alone apps to a single web application with these modules.
Any specific reason you have done a desktop app in place?

**Comment by point85** [comment]
Hello Raghu,
The Designer and Monitor desktop applications are written in JavaFX due to the heavy use of graphics and charts and callbacks from OPC DA/UA.  These applications would be difficult to do in Vaadin.

The Operator Web app is web-based since it is simple and intended for manual data entry.  The JavaFX Operator app is similarly simple, and is intended for a manual user who will accept a direct database connection in lieu of managing a web server.  On the roadmap is an Android and iOS Operator app.

**Comment by vraghu1983** [comment]
Thank you. I was looking for JavaScript libraries that can do the job of
charting. Do you think that will be a good alternative to consume the OpC
UA/Da data ?

**Comment by point85** [comment]
Hello Raghu,
I am not that familiar with JavaScript frameworks, and what open source
charting libraries might be available.  I have chosen not to use frameworks
like React, Angular or NodeJS due to the big effort in building and
maintaining an application.
